wifi_ssid: "oma_wifi"
wifi_password: "oma_wifi_salasana"
oras_venttiili_fallback_ap_password: "vaihda_tama"
oras_venttiili_api_encryption_key: "base64_api_avain_tahan"
oras_venttiili_ota_password: "vaihda_tama"
